### ISSUE TITLE
MQTT sink is not working

### ISSUE THREAD

**Issue by jprateekvmware** [spring-cloud-stream-app-starters/mqtt#2]
Hi,
Have got it running as Spring Boot App and the Binder is Kafka.
It's subscribing to kafka queue, but somehow its not able to read the message from the queue and trigger the mqtt sink call.

For me input is kafka queue and mqtt is sink.

Thanks
Prateek

**Comment by artembilan** [comment]
If you use out-of-the-box generated application, please, share logs from the application.

Otherwise share that your  Spring Boot App and provide more details how to reproduce.

Thanks

**Comment by jprateekvmware** [comment]
security.basic.enabled=false
management.security.enabled=false
management.context-path=/mgmt
eureka.instance.statusPageUrlPath=${management.context-path}${endpoints.info.path:/info}
eureka.instance.healthCheckUrlPath=${management.context-path}${endpoints.health.path:/health}
spring.cloud.stream.kafka.binder.brokers=*****
spring.cloud.stream.kafka.binder.zkNodes=*****
spring.cloud.stream.bindings.input.destination=http-kafka-KDBWOYT
spring.cloud.stream.bindings.input.group=mqtt-sink-group
spring.cloud.stream.bindings.input.binder=kafka
[pom.zip](https://github.com/spring-cloud-stream-app-starters/mqtt/files/1012354/pom.zip)

have attached the pom.xml and bootstrap configuration.

The application is starting find and below are the logs attached, but is not processing the messages from kafka queue, let me know if you need more details

[log.txt](https://github.com/spring-cloud-stream-app-starters/mqtt/files/1012358/log.txt)

**Comment by artembilan** [comment]
OK.
In the end of your logs we have:
```
2017-05-18 13:21:59,735  INFO -kafka-consumer-1 o.a.k.c.c.i.ConsumerCoordinator:256 - Setting newly assigned partitions [http-kafka-KDBWOYT-0] for group mqtt-sink-group
2017-05-18 13:21:59,822  INFO -kafka-consumer-1 o.s.c.s.b.k.KafkaMessageChannelBinder$3:247 - partitions assigned:[http-kafka-KDBWOYT-0]
```
Are you sure that there is appear some data in that partition afterwards to consume?

**Comment by garyrussell** [comment]
If you turn on DEBUG/TRACE logging for the kafka client you'll get a bunch of fetch info...

>16:21:32.301 DEBUG [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Resetting offset for partition annotated25reply2-0 to earliest offset.
...
16:21:32.302 DEBUG [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Sending fetch for partitions [annotated25reply1-1, annotated25reply1-0, annotated25reply2-1, annotated25reply2-0] to broker localhost:35572 (id: 0 rack: null)
16:21:32.304 TRACE [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Adding fetched record for partition annotated25reply1-1 with offset 0 to buffered record list
16:21:32.305 TRACE [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Received 0 records in fetch response for partition annotated25reply1-1 with offset 0
16:21:32.305 TRACE [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Adding fetched record for partition annotated25reply1-0 with offset 0 to buffered record list
16:21:32.305 TRACE [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Received 1 records in fetch response for partition annotated25reply1-0 with offset 0
16:21:32.305 TRACE [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Returning fetched records at offset 0 for assigned partition annotated25reply1-0 and update position to 1
16:21:32.305 DEBUG [Test worker][org.apache.kafka.clients.consumer.internals.Fetcher] Ignoring fetched records for annotated25reply1-0 at offset 0 since the current position is 1

**Comment by jprateekvmware** [comment]
Thanks for the responses. My bad it was pointing to wrong queue.
